# Rule Detection Database V2 — Windows Setup Script
# No Docker, No Ollama service required.
# Run in PowerShell (Administrator recommended for winget installs).

$ErrorActionPreference = "Stop"

function Write-Header([string]$text) { Write-Host "`n=== $text ===" -ForegroundColor Cyan }
function Write-Success([string]$text) { Write-Host "[+] $text" -ForegroundColor Green }
function Write-WarningMsg([string]$text) { Write-Host "[!] $text" -ForegroundColor Yellow }
function Write-ErrorMsg([string]$text) { Write-Host "[ERROR] $text" -ForegroundColor Red }

Write-Header "Rule Detection Database V2 Setup (SQLite + fastembed)"
Write-Host "No Docker or Ollama required — lightweight local stack." -ForegroundColor Magenta

if ([Environment]::OSVersion.Platform -ne "Win32NT") {
    Write-ErrorMsg "This script is for Windows. For Linux/WSL, run setup.sh instead."
    exit 1
}
Write-Success "Windows Host detected."

# ---------------------------------------------------------------------------
# 1. Dependencies
# ---------------------------------------------------------------------------
Write-Header "Checking System Dependencies"

if (!(Get-Command git -ErrorAction SilentlyContinue)) {
    Write-WarningMsg "Git not found — installing via winget..."
    winget install --id Git.Git -e --silent --accept-source-agreements --accept-package-agreements
    Write-Success "Git installed."
} else {
    Write-Success "Git: $((git --version).Trim())"
}

if (!(Get-Command python -ErrorAction SilentlyContinue)) {
    Write-WarningMsg "Python not found — installing Python 3.11 via winget..."
    winget install --id Python.Python.3.11 -e --silent --accept-source-agreements --accept-package-agreements
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    Write-Success "Python 3.11 installed."
} else {
    Write-Success "Python: $((python --version 2>&1).Trim())"
}

# ---------------------------------------------------------------------------
# 2. Port detection
# ---------------------------------------------------------------------------
Write-Header "Scanning for Port Conflicts"

function Get-NextFreePort([int]$startPort) {
    $port = $startPort
    while ($true) {
        $listeners = [System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties().GetActiveTcpListeners()
        if (-not ($listeners | Where-Object { $_.Port -eq $port })) { return $port }
        $port++
    }
}

$defaultAppPort = 8000
if ([System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties().GetActiveTcpListeners() | Where-Object { $_.Port -eq $defaultAppPort }) {
    $appPort = Get-NextFreePort ($defaultAppPort + 1)
    Write-WarningMsg "Port $defaultAppPort in use — allocated port $appPort instead."
} else {
    $appPort = $defaultAppPort
    Write-Success "Port $appPort available."
}

# ---------------------------------------------------------------------------
# 3. Generate .env
# ---------------------------------------------------------------------------
Write-Header "Generating Environment Configuration (.env)"
$envContent = @"
# Auto-generated by setup.ps1 (V2) on $(Get-Date)
APP_PORT=$appPort
DB_PATH=rule_db.db
OLLAMA_MODEL=sentence-transformers/all-MiniLM-L6-v2
"@
[System.IO.File]::WriteAllText((Join-Path (Get-Location) ".env"), $envContent)
Write-Success "Configuration saved to .env"

# ---------------------------------------------------------------------------
# 4. Python virtual environment & packages
# ---------------------------------------------------------------------------
Write-Header "Configuring Python Virtual Environment"
if (-not (Test-Path ".venv")) {
    Write-Host "Creating .venv..." -ForegroundColor Yellow
    python -m venv .venv
}
Write-Host "Installing Python packages (fastembed may take a moment)..." -ForegroundColor Yellow
& .venv\Scripts\python.exe -m pip install --upgrade pip --quiet
& .venv\Scripts\python.exe -m pip install -r requirements.txt --quiet
Write-Success "Python packages installed."

# ---------------------------------------------------------------------------
# 5. Initialize database schema
# ---------------------------------------------------------------------------
Write-Header "Initializing SQLite Database"
$env:DB_PATH = "rule_db.db"
$env:APP_PORT = $appPort
& .venv\Scripts\python.exe backend/database.py
Write-Success "SQLite database initialized (rule_db.db)."

# ---------------------------------------------------------------------------
# 6. Pre-download fastembed model
# ---------------------------------------------------------------------------
Write-Header "Pre-downloading Embedding Model (all-MiniLM-L6-v2)"
Write-Host "This downloads ~46 MB ONNX model to local cache on first run..." -ForegroundColor Yellow
$modelScript = @'
from fastembed import TextEmbedding
model = TextEmbedding("sentence-transformers/all-MiniLM-L6-v2")
emb = list(model.embed(["warmup"]))
print(f"OK:{len(emb[0].tolist())}")
'@
$modelResult = & .venv\Scripts\python.exe -c $modelScript 2>&1
if ($modelResult -like "OK:*") {
    $dims = ($modelResult -split ":")[1].Trim()
    Write-Success "Embedding model ready ($dims dimensions)."
} else {
    Write-WarningMsg "Model pre-download may have failed: $modelResult"
    Write-WarningMsg "The model will be downloaded automatically on first search."
}

# ---------------------------------------------------------------------------
# 7. Rule ingestion
# ---------------------------------------------------------------------------
if (Test-Path "rule_db_backup.sql") {
    Write-Header "Skipping ingestion — Backup file detected"
    Write-WarningMsg "V2 uses SQLite. SQL backup from V1 (PostgreSQL) is not directly compatible."
    Write-WarningMsg "Please run ingestion manually: .venv\Scripts\python.exe backend/ingest.py"
} else {
    Write-Header "Starting Rule Ingestion"
    Write-Host "Pulling rules from GitHub and generating embeddings. This takes several minutes..." -ForegroundColor Yellow
    & .venv\Scripts\python.exe backend/ingest.py
    Write-Success "Rule ingestion complete."
}

# ---------------------------------------------------------------------------
# 8. Post-install health check
# ---------------------------------------------------------------------------
Write-Header "Post-Install Health Check"
$healthScript = @'
import sys, os
sys.path.insert(0, "backend")
from database import get_db_connection
try:
    conn = get_db_connection()
    count = conn.execute("SELECT COUNT(*) FROM rules").fetchone()[0]
    conn.close()
    print(f"OK:{count}")
except Exception as e:
    print(f"FAIL:{e}")
    sys.exit(1)
'@
$healthResult = & .venv\Scripts\python.exe -c $healthScript 2>&1
if ($healthResult -like "OK:*") {
    $ruleCount = ($healthResult -split ":")[1].Trim()
    Write-Success "Database health check passed — $ruleCount rules ready."
} else {
    Write-ErrorMsg "Health check FAILED: $healthResult"
    exit 1
}

# ---------------------------------------------------------------------------
# 9. Register Task Scheduler (daily sync at 2 AM)
# ---------------------------------------------------------------------------
Write-Header "Registering Scheduled Rule Update Task"
try {
    $taskName = "RuleDatabaseAutoUpdateV2"
    if (Test-Path "cron_sync.ps1") {
        $cronPath = Resolve-Path "cron_sync.ps1"
        $trigger = New-ScheduledTaskTrigger -Daily -At "2:00 AM"
        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$cronPath`""
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
        Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Force -ErrorAction SilentlyContinue | Out-Null
        Write-Success "Task Scheduler registered: '$taskName' (daily at 2:00 AM)."
    } else {
        Write-WarningMsg "cron_sync.ps1 not found — skipping task scheduler registration."
    }
} catch {
    Write-WarningMsg "Could not register Task Scheduler. Register manually if desired."
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Header "Setup Complete!"
Write-Host ""
Write-Host "  Web Server Port : $appPort" -ForegroundColor Green
Write-Host "  Database        : rule_db.db (SQLite, no Docker needed)" -ForegroundColor Green
Write-Host "  Embeddings      : fastembed all-MiniLM-L6-v2 (ONNX, no Ollama needed)" -ForegroundColor Green
Write-Host ""
Write-Host "=== HOW TO START ===" -ForegroundColor Cyan
Write-Host "  .venv\Scripts\python.exe backend/main.py" -ForegroundColor White
Write-Host "  Then open: http://localhost:$appPort" -ForegroundColor White
Write-Host ""
Write-Host "Enjoy your lightweight offline Detection-as-Code database! — Antigravity Agent" -ForegroundColor Magenta
